name: Post animal data to DB

on:
  issues:
    types: [labeled]
  issue_comment:
    types: [created]

jobs:
  add_animal:
    if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'send-data-to-db')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract issue information
        id: extract_info
        uses: actions/github-script@v5
        with:
          script: |
            const body = context.payload.issue.body;
            const matches = body.match(/```\n([\s\S]+?)\n```/);
            const animalData = matches && matches.length > 1 ? matches[1] : null;
            console.log(animalData);
            return { animalData: animalData };

      - name: Send Data to API
        id: send_to_api
        if: steps.extract_info.outputs.animalData != null
        run: |
          curl --request POST \
            --header 'content-type: application/json' \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --url 'https://animal-kingdom-psi.vercel.app/api/graphql' \
            --data '{"query":"mutation { addAnimal(input: { data: { animalData: \"${{ steps.extract_info.outputs.animalData }}\" } }) { animal { id } }"}'

      - name: Comment on issue
        if: steps.send_to_api.success
        run: |
          echo 'Animal data has been successfully sent!'
